language: node_js
node_js: node
branches:
  only:
    - master
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
after_deploy:
  script: npm run clear
