language: node_js
node_js: node
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
after_deploy:
  script: npm run clear
