language: python
cache: pip
python:
  - "3.6"
branches:
  only:
    - master
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - sudo apt update
  - sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash
  - sudo apt-get install gcc g++ make
  - sudo apt-get install -y nodejs
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
after_deploy: npm run clear
