language: python
cache: pip
python:
  - "3.6"
branches:
  only:
    - master
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - sudo apt-get install nodejs npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
after_deploy: npm run clear
