language: node_js
node_js: node
branches:
  only:
    - master
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - python --version
    - sudo apt-get install python3.6
    - python --version
    - npm run deploy
after_deploy:
  script: npm run clear
