language: python
python:
  - "3.6"
branches:
  only:
    - master
before_install:
  - sudo apt-get install nodejs npm
install:
  - npm install
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
after_deploy:
  script: npm run clear
